import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

const repoRoot = path.join(__dirname, "..", "..");
const readme = readFileSync(path.join(repoRoot, "README.md"), "utf8");
const pkg = JSON.parse(readFileSync(path.join(repoRoot, "package.json"), "utf8")) as {
  scripts: Record<string, string>;
  devDependencies: Record<string, string>;
};

describe("README", () => {
  it("links only to images that exist", () => {
    const targets = [...readme.matchAll(/!\[[^\]]*]\(([^)]+)\)/g)]
      .map((m) => m[1])
      .filter((target) => !target.startsWith("http"));

    expect(targets.length).toBeGreaterThan(0);
    for (const target of targets) {
      expect(existsSync(path.join(repoRoot, target)), `missing image: ${target}`).toBe(true);
    }
  });

  it("keeps binary assets out of the repo root", () => {
    expect(existsSync(path.join(repoRoot, "screenshot.png"))).toBe(false);
    expect(existsSync(path.join(repoRoot, "docs", "screenshot.png"))).toBe(true);
  });

  it("documents how to regenerate the API types", () => {
    expect(readme).toContain("bun run types:generate");
  });
});

describe("generated API types", () => {
  it("have a pinned regeneration script", () => {
    // The file is generated; without a checked-in command and a pinned
    // generator it drifts from the backend and nobody can tell how it was made
    expect(pkg.scripts["types:generate"]).toContain("openapi-typescript");
    expect(pkg.scripts["types:generate"]).toContain("src/types/api.ts");
    expect(pkg.devDependencies).toHaveProperty("openapi-typescript");
  });

  it("still declare themselves generated", () => {
    const types = readFileSync(path.join(repoRoot, "src", "types", "api.ts"), "utf8");
    expect(types).toContain("auto-generated by openapi-typescript");
  });
});
