/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + data-freshness check.
         *
         *     Returns DB record counts, graph stats, and timestamps so operators can
         *     quickly tell whether GTFS data has been loaded and the graph is ready.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stops
         * @description Search stops by name substring.
         */
        get: operations["search_stops_stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reliability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reliability
         * @description Inspect the stored reliability counters behind a route's risk score.
         *
         *     Read-only, for tuning and debugging: /health reports only aggregate
         *     counts by source, which is not enough to tell whether a route scores
         *     badly because of real observations or a synthetic prior.
         *
         *     At least one of route_id or stop_id is required, and results are capped.
         *     This is a lookup tool, not a bulk export — pull the table directly if you
         *     need the whole thing.
         */
        get: operations["get_reliability_reliability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alerts
         * @description Active GTFS-RT service alerts — lets a frontend show a disruption
         *     banner without requesting routes.  Empty until RT polling is active.
         */
        get: operations["get_alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Routes
         * @description Return top-N scored routes from origin to destination.
         *
         *     Routes have real scheduled departure/arrival times for the requested date
         *     and time.  Optionally include an LLM-generated explanation of tradeoffs.
         */
        get: operations["get_routes_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/gtfs-static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Gtfs Ingest
         * @description Trigger a GTFS static data refresh, graph rebuild, and reliability
         *     reseed in the background.  (In production this also runs on a daily
         *     schedule.)
         *
         *     Returns 202 immediately — the full ingest takes ~60 s.  Poll
         *     GET /ingest/status (or /health) for completion.  409 if an ingest is
         *     already running.
         */
        post: operations["trigger_gtfs_ingest_ingest_gtfs_static_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingest Status
         * @description State of the current/most recent ingest (manual or daily refresh).
         */
        get: operations["ingest_status_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/reliability-seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Reliability Seed
         * @description Seed reliability_records from the static GTFS schedule.
         *
         *     Uses synthetic per-bucket reliability priors (no GTFS-RT required).
         *     Safe to call repeatedly — existing records are overwritten.
         *     POST /ingest/gtfs-static already reseeds; call this only to re-seed
         *     with a different window_days sample.
         */
        post: operations["trigger_reliability_seed_ingest_reliability_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertResult */
        AlertResult: {
            /** Alert Id */
            alert_id: string;
            /** Header */
            header: string;
            /** Description */
            description: string;
            /** Affected Route Ids */
            affected_route_ids: string[];
            /** Affected Stop Ids */
            affected_stop_ids: string[];
            /** Fetched At */
            fetched_at: string;
        };
        /** GtfsRtStats */
        GtfsRtStats: {
            /** Polling Active */
            polling_active: boolean;
            /** Startup Fetch Only */
            startup_fetch_only: boolean;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Backing Off Until */
            backing_off_until: string | null;
            /** Polling Coverage Since */
            polling_coverage_since: string | null;
            /** Trip Updates */
            trip_updates: number;
            /** Service Alerts */
            service_alerts: number;
            /** Vehicle Positions */
            vehicle_positions: number;
        };
        /** GtfsStats */
        GtfsStats: {
            /** Stops */
            stops: number;
            /** Trips */
            trips: number;
            /** Latest Service Date */
            latest_service_date: string | null;
            /** Graph Nodes */
            graph_nodes: number;
            /** Graph Edges */
            graph_edges: number;
            /** Graph Built */
            graph_built: boolean;
            /** Last Built At */
            last_built_at: string | null;
            /** Next Refresh At */
            next_refresh_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Timestamp */
            timestamp: string;
            gtfs: components["schemas"]["GtfsStats"];
            reliability: components["schemas"]["ReliabilityStats"];
            gtfs_rt: components["schemas"]["GtfsRtStats"];
        };
        /** IngestResponse */
        IngestResponse: {
            /**
             * Status
             * @constant
             */
            status: "accepted";
            /** Message */
            message: string;
        };
        /** IngestStatusResponse */
        IngestStatusResponse: {
            /** Running */
            running: boolean;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Last Status */
            last_status: ("ok" | "error") | null;
            /** Last Message */
            last_message: string | null;
        };
        /** LiveRisk */
        LiveRisk: {
            /** Risk Score */
            risk_score: number;
            /**
             * Risk Label
             * @enum {string}
             */
            risk_label: "Low" | "Medium" | "High";
            /** Modifiers */
            modifiers: string[];
            /** Is Cancelled */
            is_cancelled: boolean;
            /** Time Bucket */
            time_bucket: string;
            /** Scheduled Departures */
            scheduled_departures: number;
            /** Observed Departures */
            observed_departures: number;
            /** Total Delay Seconds */
            total_delay_seconds: number;
            /** Cancellation Count */
            cancellation_count: number;
            /** Source */
            source: string | null;
            /** Neutral Prior Used */
            neutral_prior_used: boolean;
        };
        /** ReliabilityResult */
        ReliabilityResult: {
            /** Route Id */
            route_id: string | null;
            /** Stop Id */
            stop_id: string | null;
            /** Time Bucket */
            time_bucket: string | null;
            /** Source */
            source: string;
            /** Scheduled Departures */
            scheduled_departures: number;
            /** Observed Departures */
            observed_departures: number;
            /** Total Delay Seconds */
            total_delay_seconds: number;
            /** Cancellation Count */
            cancellation_count: number;
            /** Window Start Date */
            window_start_date: string | null;
            /** Window End Date */
            window_end_date: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Score */
            score: number | null;
            /** Neutral Prior Used */
            neutral_prior_used: boolean;
        };
        /** ReliabilityStats */
        ReliabilityStats: {
            /** Records */
            records: number;
            /** Last Seeded At */
            last_seeded_at: string | null;
            /** By Source */
            by_source: {
                [key: string]: number;
            };
        };
        /** RoutesResponse */
        RoutesResponse: {
            /** Routes */
            routes: components["schemas"]["ScoredRoute"][];
            /** Explanation */
            explanation?: string | null;
        };
        /** ScoredRoute */
        ScoredRoute: {
            /** Legs */
            legs: (components["schemas"]["TripLeg"] | components["schemas"]["WalkLeg"])[];
            /** Total Travel Seconds */
            total_travel_seconds: number;
            /** Transfers */
            transfers: number;
            /** Total Walk Metres */
            total_walk_metres: number;
            /** Risk Score */
            risk_score: number;
            /**
             * Risk Label
             * @enum {string}
             */
            risk_label: "Low" | "Medium" | "High";
        };
        /** SeedResponse */
        SeedResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Records Written */
            records_written: number;
            /** Message */
            message: string;
        };
        /** StopResult */
        StopResult: {
            /** Stop Id */
            stop_id: string;
            /** Stop Name */
            stop_name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Routes Served */
            routes_served: string[];
        };
        /** TripLeg */
        TripLeg: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "trip";
            /** From Stop Id */
            from_stop_id: string;
            /** To Stop Id */
            to_stop_id: string;
            /** From Stop Name */
            from_stop_name: string;
            /** To Stop Name */
            to_stop_name: string;
            /** From Lat */
            from_lat?: number | null;
            /** From Lon */
            from_lon?: number | null;
            /** To Lat */
            to_lat?: number | null;
            /** To Lon */
            to_lon?: number | null;
            /** Trip Id */
            trip_id: string;
            /** Route Id */
            route_id: string;
            /** Service Id */
            service_id: string;
            /** Departure Time */
            departure_time: string;
            /** Arrival Time */
            arrival_time: string;
            /** Travel Seconds */
            travel_seconds: number;
            /** Geometry */
            geometry?: string | null;
            risk: components["schemas"]["LiveRisk"] | null;
            /** Live Delay Seconds */
            live_delay_seconds?: number | null;
            /** Expected Departure */
            expected_departure?: string | null;
            /** Expected Arrival */
            expected_arrival?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WalkLeg */
        WalkLeg: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "walk";
            /** From Stop Id */
            from_stop_id: string;
            /** To Stop Id */
            to_stop_id: string;
            /** From Stop Name */
            from_stop_name: string;
            /** To Stop Name */
            to_stop_name: string;
            /** From Lat */
            from_lat?: number | null;
            /** From Lon */
            from_lon?: number | null;
            /** To Lat */
            to_lat?: number | null;
            /** To Lon */
            to_lon?: number | null;
            /** Distance M */
            distance_m: number;
            /** Walk Seconds */
            walk_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_stops_stops_get: {
        parameters: {
            query: {
                /** @description Stop name substring to search */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reliability_reliability_get: {
        parameters: {
            query?: {
                /** @description Filter by GTFS route_id */
                route_id?: string | null;
                /** @description Filter by GTFS stop_id */
                stop_id?: string | null;
                /** @description Filter by bucket, e.g. weekday_am_peak / weekday_pm_peak / weekday_offpeak / weekend */
                time_bucket?: string | null;
                /** @description Max records */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReliabilityResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResult"][];
                };
            };
        };
    };
    get_routes_routes_get: {
        parameters: {
            query: {
                /** @description Origin stop_id */
                origin: string;
                /** @description Destination stop_id */
                destination: string;
                /** @description Earliest departure time as HH:MM or HH:MM:SS. Defaults to current time. */
                departure_time?: string | null;
                /** @description Travel date as YYYY-MM-DD. Defaults to today. */
                travel_date?: string | null;
                /** @description Latest acceptable arrival as HH:MM or HH:MM:SS, returning the latest-departing options that still make it. GTFS convention applies, so 25:30 means 01:30 the next morning. Cannot be combined with departure_time. */
                arrive_by?: string | null;
                /** @description Include LLM plain-language explanation */
                explain?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_gtfs_ingest_ingest_gtfs_static_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
        };
    };
    ingest_status_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStatusResponse"];
                };
            };
        };
    };
    trigger_reliability_seed_ingest_reliability_seed_post: {
        parameters: {
            query?: {
                /** @description Days of schedule to sample */
                window_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
